### ISSUE TITLE
未支持patch请求

### ISSUE THREAD

**Issue by 297cwrun** [fluffff/axios-miniprogram#11]
此类请求在restful接口设计中常见，且axios存在对应方法。

**Comment by fluffff** [comment]
> 此类请求在restful接口设计中常见，并且axios存在对应方法。

您好，没有实现此方法，主要是考虑微信小程序并不支持，此插件功能是以微信小程序支持情况作为标准去实现的。

**Comment by 297cwrun** [comment]
好的谢谢
