### ISSUE TITLE
小程序中无法使用,还是我接入方式不正确

### ISSUE THREAD

**Issue by mdddj** [fluffff/axios-miniprogram#35]
如图
![image](https://user-images.githubusercontent.com/29020213/132830576-a4e2f138-23c1-4917-b5ab-7f33aaeeacfe.png)
在组件中请求接口
```ts
    import axios from "axios-miniprogram";
    // 获取轮播图
    async getCarouselList(): Promise<CarouselModel[]> {
        return this.requestT<CarouselModel[]>('/carousel-list')
    }

    // 通用请求封装
    async requestT<T>(url: string, param?: any): Promise<T> {
        return new Promise<T>(async (resolve, reject) => {
            let result: undefined | Result<string> = undefined
            console.log(`典典sdk提示: platform type is ${this.platform}`)
            switch (this._platform) {
                case PlatformType.WEB:
                    
                    //web请求
                    result = await prequest<Result<string>>(`${this.url}${url}`, {
                        method: 'GET',
                        params: param
                    })
                    break
                case PlatformType.MINI:
                    //小程序请求
                   
                    let response = await axios.get<Result<string>>(`${this.url}${url}`, {
                        params: param
                    })
                    result =response.data
                
            }
            if (result) {
                successResultHandle<string>(result, data => {
                    resolve(tkDataToObject<T>(data))
                }, message => {
                    console.log(message)
                })
            }else{
                console.log('返回为空')
            }
            
        })
    }

```

把请求注释就不会报错

**Comment by fluffff** [comment]
> 如图
> ![image](https://user-images.githubusercontent.com/29020213/132830576-a4e2f138-23c1-4917-b5ab-7f33aaeeacfe.png)
> 在组件中请求接口
> 
> ```ts
>     import axios from "axios-miniprogram";
>     // 获取轮播图
>     async getCarouselList(): Promise<CarouselModel[]> {
>         return this.requestT<CarouselModel[]>('/carousel-list')
>     }
> 
>     // 通用请求封装
>     async requestT<T>(url: string, param?: any): Promise<T> {
>         return new Promise<T>(async (resolve, reject) => {
>             let result: undefined | Result<string> = undefined
>             console.log(`典典sdk提示: platform type is ${this.platform}`)
>             switch (this._platform) {
>                 case PlatformType.WEB:
>                     
>                     //web请求
>                     result = await prequest<Result<string>>(`${this.url}${url}`, {
>                         method: 'GET',
>                         params: param
>                     })
>                     break
>                 case PlatformType.MINI:
>                     //小程序请求
>                    
>                     let response = await axios.get<Result<string>>(`${this.url}${url}`, {
>                         params: param
>                     })
>                     result =response.data
>                 
>             }
>             if (result) {
>                 successResultHandle<string>(result, data => {
>                     resolve(tkDataToObject<T>(data))
>                 }, message => {
>                     console.log(message)
>                 })
>             }else{
>                 console.log('返回为空')
>             }
>             
>         })
>     }
> ```
> 
> 把请求注释就不会报错

我看你的截图上说的是页面没找到

**Comment by mdddj** [comment]
已经解决了,多谢大佬
